---
- name: Download and Unzip phpmyadmin
  unarchive:
    src: https://files.phpmyadmin.net/phpMyAdmin/4.8.3/phpMyAdmin-4.8.3-all-languages.tar.gz
    dest: /var/www/html
    remote_src : yes
    mode: 0775

- name: Copy files ~ to /var/www/html/phpmyadmin
  command: mv /var/www/html/phpMyAdmin-4.8.3-all-languages /var/www/html/phpmyadmin
    

- name: Copy phpmyadmin configuration
  template: 
    src: config.inc.php 
    dest: /var/www/html/phpmyadmin/config.inc.php
    mode: 0775

#- name: Copy php72-fpm configuration
#  template: 
#    src: default.conf 
#    dest: /etc/php-fpm.d/www.conf
#  notify: restart php72-fpm