---
- name: That is the TP2
  hosts: tp2-nginx
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - nginx
    - php72
    - phpmyadmin
  # remote_user: user
  
  #tasks: 
  #- name: Install nginx
  #  yum: name=nginx state=present

#- name: Copy nginx configuration for wordpress
 # template: src=default.conf dest=/etc/nginx/conf.d/default.conf
#notify: restart nginx